import type { Metadata } from "next";

import { Navbar } from "~/components/Navbar";

import "./globals.css";

// @todo: use website-related metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="m-auto flex min-h-screen w-full max-w-[600px] flex-col pt-[58px]">
          <Navbar />
          {children}
        </main>
      </body>
    </html>
  );
}
